// Примеры именования констант

1. ACCESS_TOKEN_VK
2. ACCESS_GROUP_ID_VK
3. ACCESS_USER_ID_VK
4. ACCESS_OWNER_ID_VK
5. CLIENT_ID
6. USER_ID
7. ACCESS_TOKEN
8. SEKRET_KEY 
9. URL
10. API_URL
11. INSTA_LOGIN
12. INSTA_PASSWORD
